package root.application.service.WeatherApp.WeatherInterfacePackage;

/**
* WeatherApp/WeatherInterfacePackage/WeatherIDLHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/IdeaProjects/wProject/src/root/application/service/Weather.idl
* 26 ������� 2014 �. 21:29:34 MSK
*/

public final class WeatherIDLHolder implements org.omg.CORBA.portable.Streamable
{
  public WeatherIDL value = null;

  public WeatherIDLHolder ()
  {
  }

  public WeatherIDLHolder (WeatherIDL initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WeatherIDLHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WeatherIDLHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WeatherIDLHelper.type ();
  }

}
