package root.application.service.WeatherApp.WeatherInterfacePackage;


/**
* WeatherApp/WeatherInterfacePackage/WeatherIDL.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/IdeaProjects/wProject/src/root/application/service/Weather.idl
* 26 ������� 2014 �. 21:29:34 MSK
*/

public final class WeatherIDL implements org.omg.CORBA.portable.IDLEntity
{
  public double temperature = (double)0;
  public double minTemperature = (double)0;
  public String cityName = null;
  public String countryName = null;
  public double windAngle = (double)0;
  public double windSpeed = (double)0;
  public String effect = null;

  public WeatherIDL ()
  {
  } // ctor

  public WeatherIDL (double _temperature, double _minTemperature, String _cityName, String _countryName, double _windAngle, double _windSpeed, String _effect)
  {
    temperature = _temperature;
    minTemperature = _minTemperature;
    cityName = _cityName;
    countryName = _countryName;
    windAngle = _windAngle;
    windSpeed = _windSpeed;
    effect = _effect;
  } // ctor

} // class WeatherIDL
