package root.application.service.WeatherApp;


import root.application.service.WeatherApp.WeatherInterfacePackage.WeatherIDL;
import root.application.service.WeatherApp.WeatherInterfacePackage.WeatherIDLHelper;

/**
* WeatherApp/_WeatherInterfaceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/IdeaProjects/wProject/src/root/application/service/Weather.idl
* 26 ������� 2014 �. 21:29:34 MSK
*/

public class _WeatherInterfaceStub extends org.omg.CORBA.portable.ObjectImpl implements WeatherInterface
{

  public WeatherIDL get (String city, String country)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("get", true);
                $out.write_string (city);
                $out.write_string (country);
                $in = _invoke ($out);
                WeatherIDL $result = WeatherIDLHelper.read($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return get (city, country        );
            } finally {
                _releaseReply ($in);
            }
  } // get

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:WeatherApp/WeatherInterface:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _WeatherInterfaceStub
