package root.application.service.WeatherApp;


import root.application.service.WeatherApp.WeatherInterfacePackage.WeatherIDL;

/**
* WeatherApp/WeatherInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/IdeaProjects/wProject/src/root/application/service/Weather.idl
* 26 ������� 2014 �. 21:29:34 MSK
*/

public interface WeatherInterfaceOperations 
{
  WeatherIDL get(String city, String country);
} // interface WeatherInterfaceOperations
