package root.application.service.WeatherApp;


import root.application.service.WeatherApp.WeatherInterfacePackage.WeatherIDL;
import root.application.service.WeatherApp.WeatherInterfacePackage.WeatherIDLHelper;

/**
* WeatherApp/WeatherInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/IdeaProjects/wProject/src/root/application/service/Weather.idl
* 26 ������� 2014 �. 21:29:34 MSK
*/

public abstract class WeatherInterfacePOA extends org.omg.PortableServer.Servant
 implements WeatherInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("get", new Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    Integer __method = (Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // WeatherApp/WeatherInterface/get
       {
         String city = in.read_string ();
         String country = in.read_string ();
         WeatherIDL $result = null;
         $result = this.get (city, country);
         out = $rh.createReply();
         WeatherIDLHelper.write(out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:WeatherApp/WeatherInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public WeatherInterface _this() 
  {
    return WeatherInterfaceHelper.narrow(
    super._this_object());
  }

  public WeatherInterface _this(org.omg.CORBA.ORB orb) 
  {
    return WeatherInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class WeatherInterfacePOA
